"use client";
import Providers from "@/src/redux/provider";
import "./globals.css";
import { Inter } from "next/font/google";
import { UserProvider } from "@/src/context/usersContext";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <Head>
          <title>e-commerce</title>
          <meta
            name="description"
            content="fully function e-commerce website"
          />
        </Head>
        <body className={inter.className}>
          <Providers>
            <UserProvider>{children}</UserProvider>
          </Providers>
        </body>
      </html>
    </>
  );
}
